### ISSUE TITLE
B站 HTML5独立播放器 支持代码

### ISSUE THREAD

**Issue by jjnnnh** [yehzhang/DanmakuCraft2#10]
`// 支持HTML5独立播放器地址`
`// @match        *://www.bilibili.com/blackboard/*player.html?aid=19771370`
`// @match        *://www.bilibili.com/blackboard/*player.html?aid=19771370&*`
`// @match        *://www.bilibili.com/blackboard/*player.html?bvid=1GW41177LA`
`// @match        *://www.bilibili.com/blackboard/*player.html?bvid=1GW41177LA&*`
`// @match        *://www.bilibili.com/blackboard/*player.html?bvid=BV1GW41177LA`
`// @match        *://www.bilibili.com/blackboard/*player.html?bvid=BV1GW41177LA&*`

**Comment by jjnnnh** [comment]
示例链接：
[旧播放器](https://www.bilibili.com/blackboard/html5player.html?aid=19771370&cid=32239646)、[新播放器](https://www.bilibili.com/blackboard/player.html?aid=19771370)、[新播放器](https://www.bilibili.com/blackboard/newplayer.html?bvid=BV1GW41177LA)

**Comment by yehzhang** [comment]
感谢指出 B 站还有独立播放器！你可以 Make a pull request 吗？

**Comment by jjnnnh** [comment]
> 感谢指出 B 站还有独立播放器！你可以 Make a pull request 吗？

https://github.com/yehzhang/DanmakuCraft2/pull/12

**Comment by jjnnnh** [comment]
> 感谢指出 B 站还有独立播放器！你可以 Make a pull request 吗？

https://github.com/yehzhang/DanmakuCraft2/pull/12
